# Generated by Django 5.1.4 on 2024-12-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_publisher_alter_author_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['degree_of_wear']},
        ),
    ]
