# Generated by Django 5.1.4 on 2024-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='degree_of_wear',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'publisher', 'published_year')},
        ),
    ]
