# Generated by Django 5.1.4 on 2024-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_condition_degree_of_wear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='statements/default_cover.png', upload_to='covers/'),
        ),
    ]
