# Generated by Django 5.1.4 on 2024-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='/home/domini/PycharmProjects/UsedBookStore/UsedBookStore/statements/default_cover.png', upload_to='covers/'),
        ),
    ]
