# Generated by Django 5.1.4 on 2024-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='statements/default_cover.png', null=True, upload_to='covers/'),
        ),
    ]
