# Generated by Django 5.1.4 on 2024-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='cover/default_cover.jpg', upload_to='covers/'),
        ),
    ]
