# Generated by Django 5.1.4 on 2024-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('reserved', 'Зарезервировано'), ('sold', 'Продано'), ('lost', 'Потеряно')], default='in_stock', max_length=20),
        ),
    ]
