# Generated by Django 5.1.4 on 2024-12-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_bookinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='reserved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_book_instances', to='Store.profile'),
        ),
    ]
