# Generated by Django 5.1.4 on 2024-12-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_bookinstance_reserved_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='reserved_by_user',
            new_name='reserved_by_profile',
        ),
    ]
